import Link from "next/link"
import { ArrowLeft, Check, Heart, MapPin, ShieldCheck, Star } from "lucide-react"
import { products } from "@/lib/products"
import { Shell } from "@/components/dashboard-ui"

export default async function ProductDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const product = products.find(item => item.id === id) ?? products[0]
  const discount = Math.round((1 - product.price / product.oldPrice) * 100)
  return <Shell title="Product details" back><div className="mx-auto max-w-5xl px-5 py-8 pb-28 md:px-10 md:pb-12"><Link href="/dashboard" className="mb-6 inline-flex items-center gap-2 text-sm text-black/50"><ArrowLeft size={16}/> Back to deals</Link><div className="grid gap-8 rounded-3xl border border-black/[.07] bg-white p-4 md:grid-cols-2 md:p-7"><div className="relative overflow-hidden rounded-2xl bg-[#f5f4f5]"><img src={product.image} alt={product.name} className="h-[320px] w-full object-cover md:h-[460px]"/><span className="absolute left-4 top-4 rounded-full bg-[#171719] px-3 py-1.5 text-xs font-bold text-white">-{discount}% today</span></div><div className="flex flex-col justify-center py-2 md:px-4"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#7d5cff]">AI recommended</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.06em] md:text-4xl">{product.name}</h2><p className="mt-2 text-sm text-black/50">{product.seller}</p><div className="mt-5 flex items-center gap-2 text-sm"><Star size={16} fill="#f4c542" className="text-[#f4c542]"/> 4.8 (196 reviews)</div><div className="mt-7 flex items-end gap-3"><span className="text-3xl font-bold">₹{product.price.toLocaleString("en-IN")}</span><span className="text-sm text-black/35 line-through">₹{product.oldPrice.toLocaleString("en-IN")}</span></div><div className="mt-5 flex items-center gap-2 text-sm text-emerald-700"><MapPin size={16}/> {product.delivery}</div><div className="my-7 border-t border-black/[.07] pt-5"><p className="text-sm font-semibold">Why the agent likes it</p><ul className="mt-3 space-y-3 text-sm text-black/60"><li className="flex items-center gap-2"><Check size={15} className="text-emerald-600"/> Best price found across 12 stores</li><li className="flex items-center gap-2"><ShieldCheck size={15} className="text-emerald-600"/> Verified seller and easy returns</li><li className="flex items-center gap-2"><Check size={15} className="text-emerald-600"/> Price is predicted to stay low</li></ul></div><div className="flex gap-3"><button className="flex-1 rounded-full bg-[#171719] px-5 py-3.5 text-sm font-semibold text-white">View best deal</button><button aria-label="Save product" className="grid size-12 place-items-center rounded-full border border-black/10"><Heart size={18}/></button></div></div></div></div></Shell>
}
