export type OrderStatus = "Processing" | "On the way" | "Delivered" | "Issue"
export type OrderKind = "standard" | "quick" | "pickup" | "digital"
export type OrderFilter = "All" | OrderStatus | "Returns / issues"

export type TaxLine = { name: string; amount: number; included: boolean }

export const presentTaxLines = (taxes: TaxLine[]) => taxes.filter((tax) => tax.amount > 0 && tax.name.trim().length > 0)
export type OrderPricing = { currency: string; locale: string; itemSubtotal: number; deliveryFee: number; discount: number; savings: number; taxes: TaxLine[]; total: number }
export type OrderItem = { name: string; quantity: string; price: number }
export type PurchaseReview = { id: string; product: { name: string; image: string }; seller: string; fulfillment: { kind: OrderKind; method: string; location: string; eta: string }; pricing: OrderPricing; paymentMethod: string; agentDecision: { summary: string; factors: string[]; savings: number }; guardrails: { label: string; passed: boolean }[]; autonomy: "recommend-only" | "approve-and-buy" | "delegated-auto-buy"; approvalRequired: boolean }

export const purchaseReview: PurchaseReview = { id: "review-sony-260913", product: { name: "Sony WH-1000XM5", image: "/products/sony-wh-1000xm5.png" }, seller: "Croma", fulfillment: { kind: "standard", method: "Home delivery", location: "Indiranagar, Bengaluru", eta: "Arriving tomorrow" }, pricing: { currency: "INR", locale: "en-IN", itemSubtotal: 4399, deliveryFee: 0, discount: 0, savings: 300, taxes: [], total: 4399 }, paymentMethod: "UPI · •••• 4821", agentDecision: { summary: "Best available option for your requirements.", factors: ["Best available price", "Matches your budget", "Delivery meets your requirement", "Trusted seller"], savings: 300 }, guardrails: [{ label: "Within your budget", passed: true }, { label: "Seller allowed", passed: true }, { label: "Delivery requirement met", passed: true }, { label: "Purchase limit respected", passed: true }], autonomy: "approve-and-buy", approvalRequired: true }

export const approvePurchaseReview = async (id: string) => { const response = await fetch(`/api/purchase-reviews/${id}/approve`, { method: "POST" }); const payload = await response.json().catch(() => null) as { error?: string; reason?: string } | null; if (!response.ok) throw new Error(payload?.reason || payload?.error || "Purchase couldn't be completed."); return payload }
export type PostPurchase = { returnEligible: boolean; exchangeEligible: boolean; refundEligible: boolean; supportAvailable: boolean; returnWindow: string; refundStatus: "Not requested" | "Refund requested" | "Refund processing" | "Refund completed"; refundAmount: number; refundMethod: string; refundProcessingTime: string }
export type CommerceOrder = {
  id: string; kind: OrderKind; title: string; seller: string; amount: number; budgetLimit?: number; savings: number; status: OrderStatus; eta: string; date: string; image: string; location?: string
  items: OrderItem[]; pricing: OrderPricing; delivery: { location: string; method: string; estimated: string }; payment: string; reference: string
  decision: string; decisionFactors: string[]; decisionReason: string; eligibleForQuickDelivery: boolean; postPurchase?: PostPurchase
  timeline: { label: string; detail: string; done: boolean; current?: boolean }[]
}

const indiaPricing = (itemSubtotal: number, deliveryFee: number, discount: number, savings: number, total: number, taxes: TaxLine[] = []): OrderPricing => ({ currency: "INR", locale: "en-IN", itemSubtotal, deliveryFee, discount, savings, taxes, total })

export const orders: CommerceOrder[] = [
  { id: "order-sony", kind: "standard", title: "Sony WH-1000XM5", seller: "Croma", amount: 4399, savings: 300, status: "On the way", eta: "Arriving tomorrow", date: "13 September 2026", image: "/products/sony-wh-1000xm5.png", items: [{ name: "Sony WH-1000XM5", quantity: "1 item", price: 4399 }], pricing: indiaPricing(4399, 0, 0, 300, 4399), delivery: { location: "Indiranagar, Bengaluru", method: "Home delivery", estimated: "Arriving tomorrow" }, payment: "UPI · •••• 4821", reference: "SA-260913-SONY", decision: "Best option found", decisionFactors: ["₹300 below the next-best available option", "Available for tomorrow delivery"], decisionReason: "ShopAgent found this for ₹4,399 — ₹300 less than the next-best available option.", eligibleForQuickDelivery: false, timeline: [{ label: "Order confirmed", detail: "13 Sep · 10:42 AM", done: true }, { label: "Seller preparing", detail: "Croma warehouse", done: true }, { label: "Out for delivery", detail: "Expected tomorrow", done: false, current: true }, { label: "Delivered", detail: "We&apos;ll notify you", done: false }] },
  { id: "order-groceries", kind: "quick", title: "Weekly groceries", seller: "Zepto", amount: 371, budgetLimit: 500, savings: 29, status: "On the way", eta: "Arriving in ~12 min", date: "13 September 2026", image: "/products/grocery-basket.png", items: [{ name: "Milk", quantity: "2 L", price: 112 }, { name: "Eggs", quantity: "12", price: 96 }, { name: "Bread", quantity: "1 pack", price: 54 }, { name: "Biscuits", quantity: "2 packs", price: 109 }], pricing: indiaPricing(371, 0, 0, 29, 371), delivery: { location: "Indiranagar, Bengaluru", method: "Quick delivery", estimated: "Arriving in ~12 min" }, payment: "UPI · •••• 4821", reference: "SA-260913-ZEPTO", decision: "Best option found", decisionFactors: ["Fastest complete basket", "Within your grocery budget"], decisionReason: "ShopAgent found the fastest complete basket within your grocery budget.", eligibleForQuickDelivery: true, timeline: [{ label: "Preparing order", detail: "Zepto store", done: true }, { label: "Picked up", detail: "Rider has the order", done: true }, { label: "On the way", detail: "Arriving in ~12 min", done: false, current: true }, { label: "Arriving soon", detail: "At your door", done: false }] },
  { id: "order-backpack", kind: "standard", title: "Lightweight travel backpack", seller: "Amazon India", amount: 2899, savings: 600, status: "Delivered", eta: "Delivered today", date: "10 September 2026", image: "/products/travel-backpack.png", items: [{ name: "Lightweight travel backpack", quantity: "1 item", price: 2899 }], pricing: indiaPricing(2899, 0, 0, 600, 2899), delivery: { location: "Indiranagar, Bengaluru", method: "Home delivery", estimated: "Delivered today" }, payment: "UPI · •••• 4821", reference: "SA-260910-BAG", postPurchase: { returnEligible: true, exchangeEligible: true, refundEligible: true, supportAvailable: true, returnWindow: "Until 24 September 2026", refundStatus: "Not requested", refundAmount: 2899, refundMethod: "Original UPI method", refundProcessingTime: "3–5 business days" }, decision: "Best option found", decisionFactors: ["Strongest value score", "Matched your lightweight preference"], decisionReason: "ShopAgent found the strongest value match for your lightweight preference.", eligibleForQuickDelivery: false, timeline: [{ label: "Order confirmed", detail: "10 Sep · 8:12 AM", done: true }, { label: "Seller preparing", detail: "Amazon fulfillment", done: true }, { label: "Out for delivery", detail: "10 Sep · 1:02 PM", done: true }, { label: "Delivered", detail: "10 Sep · 3:18 PM", done: true }] },
]

export const savedItems = [{ name: "Sony WH-1000XM5", detail: "Prefers pickup when nearby", image: "/products/sony-wh-1000xm5.png" }, { name: "Travel backpack", detail: "Lightweight, under ₹4,000", image: "/products/travel-backpack.png" }, { name: "Running shoes", detail: "Revisit before next weekend", image: "/products/travel-backpack.png" }]
export const memories = ["Prefers faster delivery when the price difference is small", "Usually keeps electronics under ₹5,000", "Prefers lightweight travel gear"]
export const quickOptions = [{ name: "Zepto", eta: "~16 min", total: 371, distance: "2.1 km" }, { name: "Nearby supermarket", eta: "Pickup in ~8 min", total: 342, distance: "0.8 km" }]
export const formatMoney = (value: number, pricing: Pick<OrderPricing, "currency" | "locale">) => new Intl.NumberFormat(pricing.locale || undefined, { style: "currency", currency: pricing.currency, maximumFractionDigits: pricing.currency === "INR" ? 0 : 2 }).format(value)
export const formatINR = (value: number) => formatMoney(value, { currency: "INR", locale: "en-IN" })
export const orderById = (id: string) => orders.find((order) => order.id === id)
export const matchesFilter = (order: CommerceOrder, filter: OrderFilter) => filter === "All" || (filter === "Returns / issues" ? order.status === "Issue" : order.status === filter)
export const orderKindLabel = (kind: OrderKind) => ({ standard: "Standard delivery", quick: "Quick delivery", pickup: "Pickup", digital: "Digital delivery" })[kind]
export const commerceService = { listOrders: async () => orders, getOrder: async (id: string) => orderById(id), requestReturn: async (id: string) => ({ id, status: "requested" as const }), contactSupport: async (id: string) => ({ id, status: "opened" as const }) }
